name: rr
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - fastparquet
  - geopandas
  - netcdf4
  - networkx
  - numba
  - numpy
  - pandas
  - pyyaml
  - scipy
  - shapely
  - tqdm
  - xarray
  - zarr
  # in development
  - pandas-stubs
  - scipy-stubs
  # for documentation
  - mkdocs<2
  - mkdocs-material
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-include-markdown-plugin
