name: rr
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - dask
  - fastparquet
  - matplotlib
  - natsort
  - netcdf4
  - networkx
  - numpy
  - pandas
  - pyyaml
  - scipy
  - tqdm
  - xarray
  - zarr