site_name: River Route
site_url: https://river-route.code.hales.app
copyright: Copyright &copy; 2023-2026 Dr Riley Hales. All rights reserved.
theme:
  name: material
  palette:
    primary: light blue
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.path
    - navigation.footer
    - toc.follow
nav:
  - Home: index.md
  - License: terms.md
  - API Documentation: api.md
  - Changelog: changelog.md
  - References:
      - The Config File: references/config-files.md
      - File Schemas: references/io-file-schema.md
      - Time Variables: references/time-variables.md
  - Tutorials:
      - Preparing Watersheds: tutorial/prepare-watersheds.md
      - Channel Routing: tutorial/channel-routing.md
      - Channel Routing with Runoff Transform: tutorial/unit-hydrograph-routing.md
      - Routing Runoff Ensembles: tutorial/routing-ensembles.md
      - Advanced Uses: tutorial/advanced-tutorial.md
      - Generating UH Kernels: tutorial/create-uh-kernels.md
  - Migration Guides:
      - v1 to v2: migrating/v1-to-v2.md
plugins:
  - search
  - mkdocstrings
  - include-markdown:
      comments: false
markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
