site_name: River Route
site_url: https://rr.hales.app
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
nav:
  - Home: index.md
  - Config Files:
      - Config Options: configs/config-options.md
      - Input & Output Files: configs/io-files.md
      - Time Variables: configs/time-variables.md
  - API Documentation: api.md
  - Saving Outputs: saving-outputs.md
plugins:
  - search
  - mkdocstrings
  - include-markdown:
      comments: false
markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format