site_name: River Route
site_url: https://river-route.code.hales.app
copyright: Copyright &copy; 2023-2026 Dr Riley Hales. All rights reserved.
theme:
  name: material
  palette:
    primary: light blue
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.path
    - navigation.footer
    - toc.follow
nav:
  - Home: index.md
  - License: terms.md
  - Changelog: changelog.md
  - API Docs:
      - Router Classes: api/routers.md
      - Unit Hydrographs: api/unit-hydrographs.md
      - Tools: api/tools.md
  - References:
      - The Config File: references/config-files.md
      - File Schemas: references/io-file-schema.md
      - Time Variables: references/time-options.md
      - No Parallelism: references/parallelism.md
      - Math Derivations: references/math.md
      - Forward Substitution: references/forward-substitution.md
      - Test Data: references/test-data.md
  - Tutorials:
      - Basics: tutorial/basics.md
      - Unit Hydrographs with Routing: tutorial/unit-hydrograph-routing.md
      - Routing Runoff Ensemble: tutorial/routing-ensembles.md
      - Advanced Uses: tutorial/advanced.md
  - Migration Guides:
      - v1 to v2: migrating/v1-to-v2.md
plugins:
  - search
  - mkdocstrings
  - include-markdown:
      comments: false
extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - javascripts/katex.js
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
