site_name: River Route
site_url: https://rr.hales.app
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
nav:
  - Home: index.md
  - API Documentation: pages/api.md
  - Configs:
      - Config File: pages/config-files.md
      - Input/Output File Schemas: pages/io-file-schema.md
      - Time Variables: pages/time-variables.md
  - Basic Tutorial: pages/tutorial.md
  - Advanced Tutorial: pages/tutorial-advanced.md
plugins:
  - search
  - mkdocstrings
  - include-markdown:
      comments: false
markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format