[project]
site_name = "River Route"
site_url = "https://river-route.code.hales.app"
copyright = "Copyright &copy; 2023-2026 Dr Riley Hales. All rights reserved."
nav = [
  { "Home" = "index.md" },
  { "License" = "terms.md" },
  { "Changelog" = "changelog.md" },
  { "API Docs" = [
    { "Configs" = "api/configs.md" },
    { "Runoff" = "api/runoff.md" },
    { "Router" = "api/routers.md" },
    { "Writers" = "api/writers.md" },
    { "Tools" = "api/tools.md" },
  ] },
  { "References" = [
    { "The Config File" = "references/config-files.md" },
    { "File Schemas" = "references/io-file-schema.md" },
    { "Time Variables" = "references/time-options.md" },
    { "Math Derivations" = "references/math.md" },
    { "Parallelism" = "references/parallelism.md" },
  ] },
  { "Tutorials" = [
    { "Basics" = "tutorial/basics.md" },
    { "Routing Runoff Ensemble" = "tutorial/routing-ensembles.md" },
    { "Advanced Uses" = "tutorial/advanced.md" },
  ] },
  { "Migration Guides" = [
    { "v1 to v2" = "migrating/v1-to-v2.md" },
  ] },
]
extra_javascript = [
  "https://unpkg.com/katex@0/dist/katex.min.js",
  "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js",
  "static/js/katex.js",
]
extra_css = [
  "https://unpkg.com/katex@0/dist/katex.min.css",
  "static/css/custom.css",
]

[project.theme]
features = [
  "content.code.copy",
  "content.code.select",
  "navigation.expand",
  "navigation.path",
  "navigation.footer",
  "toc.follow",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "light blue"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "light blue"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.plugins.mkdocstrings]

[project.markdown_extensions.admonition]

[project.markdown_extensions.attr_list]

[project.markdown_extensions."pymdownx.snippets"]
check_paths = true

[project.markdown_extensions."pymdownx.details"]

[project.markdown_extensions."pymdownx.emoji"]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions."pymdownx.arithmatex"]
generic = true

[project.markdown_extensions."pymdownx.superfences"]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
