# Required Watershed Files
routing_params_file: ''
connectivity_file: ''
# Volume Inputs - (Option 1)
catchment_volumes_file: ''
# Depth Inputs - (Option 2)
runoff_depths_files: ''
weight_table_file: ''
# Output file
outflow_file: ''
# Compute Options
routing: 'linear'  # linear or nonlinear
input_type: 'sequential'  # sequential or ensemble
runoff_type: 'incremental'  # incremental or cumulative
dt_routing: 0  # defaults to time step of volume inputs
dt_outflows: 0  # defaults to time step of volume inputs
solver_atol: 0.00001
# initial and final state files
initial_state_file: ''
final_state_file: ''
# simulation management and debugging
log: False
progress_bar: False
log_level: 'DEBUG'
log_stream: ''
job_name: ''
# Variable names expected in the netCDF input/output files
var_x: 'lon'
var_y: 'lat'
var_t: 'time'
var_runoff_depth: 'ro'
var_catchment_volume: 'volume'
var_river_id: 'river_id'
var_outflow: 'Q'
