# Required Watershed Files
routing_params_file: ''
connectivity_file: ''
# Routing Input and Output
runoff_volumes_file: ''
outflow_file: ''
# Input and Output file structure - Optional
var_runoff_volume: 'ro_vol'
var_river_id: 'river_id'
var_outflow: 'Q'
# Compute Options - Optional
routing: 'linear'
positive_flow: True
dt_routing: 0
dt_outflows: 0
# initial and final state files - Optional
initial_state_file: ''
final_state_file: ''
# simulation management and debugging - Optional
log: False
progress_bar: False
log_level: 'DEBUG'
log_stream: ''
job_name: ''
