# paths to watershed files - Required
routing_params_file: ''
connectivity_file: ''
# runoff inflows - Required
runoff_file: ''
# routed discharge outputs - Required - list of absolute path strings even if only one file
outflow_file: ''
# computation time parameters - all times given in seconds - Required
dt_outflows: 0
dt_routing: 300
# simulation management and debugging - Optional
job_name: ''
log_file: ''
routing_method: ''
progress_bar: True
# cache routing matrices - Optional
lhs_file: ''
lhsinv_file: ''
adj_file: ''
# Optional - PETSc solver options
petsc_ksp_type: ''
# initial and final state files - Optional
qinit_file: ''
rinit_file: ''
qfinal_file: ''
rfinal_file: ''

